### ISSUE TITLE
udf in reduce_dimension works with t, fails with time dim name

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-udf-python-to-r#26]
https://github.com/Open-EO/openeo-udf-python-to-r/blob/61aaae593de22a1ac1c3c600e2ccee6dc9c195b6/src/openeo_r_udf/executor.R#L19

@m-mohr, a udf is failing when the dimension is called "t" (as on eurac) but works when we rename the dim to "time" (as on vito).
see here for reference: https://github.com/Open-EO/r4openeo-usecases/blob/main/uc2-ts-breakdetection/local_udf/run_bfast_udf.ipynb

**Comment by m-mohr** [comment]
I can't reproduce it, if I change the temporal dimension from t to time in the test.py it works flawlessly.
Please check whether you are running the latest version and if that's the case, can you please provide a minimal reprex?

**Comment by clausmichele** [comment]
@m-mohr I can reproduce it, I run this code in the folder /r4openeo-usecases/uc2-ts-breakdetection/local_udf

```
from os import getcwd
import openeo_r_udf
from openeo_r_udf.udf_lib import prepare_udf, execute_udf
import time
import xarray as xr

print(openeo_r_udf.__version__)

# config
# load_file = "../00_data_local/vaja.nc/openEO.nc"
load_file = "../00_data_local/test_eurac.nc"
udf_file = "../00_udfs/bfast_udf.R"
save_file = "./results/local_udf_test.tif"
dimension = "t"
context = {'start_monitor': 2018}

# load and prepare data - depending on your data structure
# dataset_vito = xr.open_dataset(load_file, engine = 'h5netcdf', decode_coords = 'all')
dataset = xr.open_dataset(load_file, engine = 'h5netcdf', decode_coords = 'all')

# dataset = dataset.rename({"time":"t"}) # Uncommenting this makes the code work

# define runer for udf
def run(process, udf, data = None, dimension = None, context = None):
    # Run UDF executor
    t1 = time.time() # Start benchmark
    print('start: ', udf) #t1
    result = execute_udf(process, udf, data, dimension = dimension, context = context)
    t2 = time.time() # End benchmark
    print('end: ', udf) #t2

    # Print result and benchmark
    print('  Time elapsed: %s' % (t2 - t1))
    #save_result(result, save_file)
    
    
print('reduce_dimension bfast')
run('reduce_dimension', udf_file, data = dataset, dimension = dimension, context = context)
```

```
~/r4openeo-usecases/uc2-ts-breakdetection/local_udf$ python test.py 
0.4.0
reduce_dimension bfast
start:  ../00_udfs/bfast_udf.R
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    run('reduce_dimension', udf_file, data = dataset, dimension = dimension, context = context)
  File "test.py", line 28, in run
    result = execute_udf(process, udf, data, dimension = dimension, context = context)
  File "/home/mclaus@eurac.edu/anaconda3/envs/openeo_odc/lib/python3.8/site-packages/openeo_r_udf/udf_lib.py", line 22, in execute_udf
    output_dims.remove(dimension)
ValueError: list.remove(x): x not in list
```

**Comment by m-mohr** [comment]
The file you are loading is `../00_data_local/test_eurac.nc`, right? It has a `time` dimension. The code you are running has `dimension` set to `t` though?! That fails if your dimension is not called `t`, of course. Please update the variable assignment and try again.

**Comment by clausmichele** [comment]
I've just found out the same thing, @przell you where assigning the wrong name to the dimension to reduce :)
`dimension = "t"` instead of `dimension = "time"`
